server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yff?characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.example.springbootmybatis.entity
